/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algo.Ex2;

public class MyApp {
    public String getGreeting() {
        return "Testing from Gradle!";
    }

    public static void main(String[] args) {
        
        System.out.println("Hello World!");
    }
}
